### ISSUE TITLE
which opencv version is recommended?

### ISSUE THREAD

**Issue by oscarriddle** [Tencent/ncnn#843]
I tried to install opencv4.0.1 and build with gcc5.3
Then I got below error when compiling caffe component, it seems that gcc version is not compatible with opencv.
```
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_videoio.so.4.0.1: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_imgcodecs.so.4.0.1: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
collect2: error: ld returned 1 exit status
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_videoio.so.4.0.1: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_imgcodecs.so.4.0.1: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
make[2]: collect2: error: ld returned 1 exit status
*** [examples/squeezenetssd] Error 1
make[1]: *** [examples/CMakeFiles/squeezenetssd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [examples/mobilenetssd] Error 1
make[1]: *** [examples/CMakeFiles/mobilenetssd.dir/all] Error 2
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_videoio.so.4.0.1: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_imgcodecs.so.4.0.1: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/squeezenet] Error 1
make[1]: *** [examples/CMakeFiles/squeezenet.dir/all] Error 2
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_videoio.so.4.0.1: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/web_server/xiaolun/install/opencv-4.0.1/build/lib/libopencv_imgcodecs.so.4.0.1: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/fasterrcnn] Error 1
make[1]: *** [examples/CMakeFiles/fasterrcnn.dir/all] Error 2
make: *** [all] Error 2

```

What are the recommended opencv and gcc versions?

**Comment by nihui** [comment]
the latest example code is compatible with opencv 2.x ~ 4.x.
it seems that your opencv installation is broken
