### ISSUE TITLE
undefined reference to `typeinfo for ncnn::Layer' collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by SinemVisea** [Tencent/ncnn#4797]
## detail | 详细描述 | 詳細な説明
Hi!
I am working on Raspberry Pi 4 Model B Rev 1.5.

I want to run yoloV5 according to https://github.com/Qengineering/YoloV5-ncnn-Raspberry-Pi-4 instructions.

/usr/bin/ld: /tmp/ccA55Dwy.o:(.data.rel.ro._ZTI11YoloV5Focus[_ZTI11YoloV5Focus]+0x10): undefined reference to `typeinfo for ncnn::Layer'
collect2: error: ld returned 1 exit status

I deleted ncnn and OpenCV and reinstalled.
Also set "NCNN_DISABLE_RTTI=OFF" but it doesn't fix it. Is there any other method you can suggest?
